FROM node:24-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

FROM deps AS build

ARG NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=https://download.webtuichat.com/desktop
ARG NEXT_PUBLIC_MOBILE_DOWNLOAD_URL=https://download.webtuichat.com/mobile
ARG NEXT_PUBLIC_DOCUMENTATION_URL=https://docs.webtuichat.com
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ENV NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=$NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL
ENV NEXT_PUBLIC_MOBILE_DOWNLOAD_URL=$NEXT_PUBLIC_MOBILE_DOWNLOAD_URL
ENV NEXT_PUBLIC_DOCUMENTATION_URL=$NEXT_PUBLIC_DOCUMENTATION_URL
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH

COPY . .
RUN npm run build

FROM node:24-alpine AS runner

WORKDIR /app
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3002
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH

COPY --from=build /app ./

EXPOSE 3002

CMD ["npm", "run", "start"]
