FROM node:24-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

FROM deps AS build

ARG NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=https://download.webtui.vn/download/
ARG NEXT_PUBLIC_MOBILE_DOWNLOAD_URL
ARG NEXT_PUBLIC_DOCUMENTATION_URL=https://download.webtui.vn/#self-host
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ARG ACCOUNT_DELETION_COMPLETION_DAYS
ARG APPLE_BUNDLE_ID
ARG APPLE_TEAM_ID
ARG APP_LINK_ORIGIN
ARG ENABLE_IOS_ASSOCIATION=false
ARG LEGAL_ENTITY_ADDRESS
ARG LEGAL_ENTITY_COUNTRY
ARG LEGAL_ENTITY_NAME
ARG MODERATION_EVIDENCE_RETENTION_DAYS
ARG PLAY_APP_SIGNING_SHA256_FINGERPRINTS
ARG POLICY_EFFECTIVE_DATE
ARG POLICY_VERSION
ARG PORTAL_ORIGIN
ARG PRIVACY_CONTACT_EMAIL
ARG SAFETY_CONTACT_EMAIL
ARG SUPPORT_EMAIL
ARG SUPPORT_RESPONSE_HOURS
ARG UGC_REPORT_RESPONSE_HOURS
ENV NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=$NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL
ENV NEXT_PUBLIC_MOBILE_DOWNLOAD_URL=$NEXT_PUBLIC_MOBILE_DOWNLOAD_URL
ENV NEXT_PUBLIC_DOCUMENTATION_URL=$NEXT_PUBLIC_DOCUMENTATION_URL
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH
ENV ACCOUNT_DELETION_COMPLETION_DAYS=$ACCOUNT_DELETION_COMPLETION_DAYS
ENV APPLE_BUNDLE_ID=$APPLE_BUNDLE_ID
ENV APPLE_TEAM_ID=$APPLE_TEAM_ID
ENV APP_LINK_ORIGIN=$APP_LINK_ORIGIN
ENV ENABLE_IOS_ASSOCIATION=$ENABLE_IOS_ASSOCIATION
ENV LEGAL_ENTITY_ADDRESS=$LEGAL_ENTITY_ADDRESS
ENV LEGAL_ENTITY_COUNTRY=$LEGAL_ENTITY_COUNTRY
ENV LEGAL_ENTITY_NAME=$LEGAL_ENTITY_NAME
ENV MODERATION_EVIDENCE_RETENTION_DAYS=$MODERATION_EVIDENCE_RETENTION_DAYS
ENV PLAY_APP_SIGNING_SHA256_FINGERPRINTS=$PLAY_APP_SIGNING_SHA256_FINGERPRINTS
ENV POLICY_EFFECTIVE_DATE=$POLICY_EFFECTIVE_DATE
ENV POLICY_VERSION=$POLICY_VERSION
ENV PORTAL_ORIGIN=$PORTAL_ORIGIN
ENV PRIVACY_CONTACT_EMAIL=$PRIVACY_CONTACT_EMAIL
ENV SAFETY_CONTACT_EMAIL=$SAFETY_CONTACT_EMAIL
ENV SUPPORT_EMAIL=$SUPPORT_EMAIL
ENV SUPPORT_RESPONSE_HOURS=$SUPPORT_RESPONSE_HOURS
ENV UGC_REPORT_RESPONSE_HOURS=$UGC_REPORT_RESPONSE_HOURS

COPY . .
RUN npm run build

FROM node:24-alpine AS runner

WORKDIR /app
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3002
ENV HOSTNAME=0.0.0.0
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

EXPOSE 3002

CMD ["node", "server.js"]
