FROM node:24-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

FROM deps AS build

ARG NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=https://download.vpsttt.com/download/
ARG NEXT_PUBLIC_MOBILE_DOWNLOAD_URL=https://download.vpsttt.com/download/
ARG NEXT_PUBLIC_DOCUMENTATION_URL=https://download.vpsttt.com/#self-host
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@vpsttt.com
ENV NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL=$NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL
ENV NEXT_PUBLIC_MOBILE_DOWNLOAD_URL=$NEXT_PUBLIC_MOBILE_DOWNLOAD_URL
ENV NEXT_PUBLIC_DOCUMENTATION_URL=$NEXT_PUBLIC_DOCUMENTATION_URL
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL

COPY . .
RUN npm run build

FROM node:24-alpine AS runner

WORKDIR /app
ARG NEXT_PUBLIC_PORTAL_BASE_PATH=
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3002
ENV HOSTNAME=0.0.0.0
ENV NEXT_PUBLIC_PORTAL_BASE_PATH=$NEXT_PUBLIC_PORTAL_BASE_PATH

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
COPY --from=build /app/download ./download

EXPOSE 3002

CMD ["node", "server.js"]
